#versions: myenv, binderenv, myenvextras
name: voila-gallery
channels:
- conda-forge
dependencies:
- matplotlib-base
- pandas
- ipywidgets
- jupyterlab>=3.1
- voila>=0.2.11
- numpy==1.24.3
- scikit-learn==1.3.0
- scipy==1.10.1
- seaborn==0.12.2
- widgetsnbextension==3.5.2

  
#dependencies:
#  - python==3.8.10 #
#  - numpy==1.24.3
#  - scikit-learn==1.3.0
#  - scipy==1.10.1 
#  - seaborn==0.12.2
#  - ipywidgets==7.6.5
#  - matplotlib==3.7.1
#  - widgetsnbextension==3.5.2
#  - voila==0.3.7
#  - jupyter
#  - notebook==6.5.4


